@startuml
class cubibon.callAssistant.llm.message.AwsMessage$Builder {
+ void public()
}

class cubibon.callAssistant.llm.message.AwsMessage$Companion {
+ LlmMessage.Builder<Message> build(CentralizedLogger)
}

class cubibon.callAssistant.llm.message.AwsMessage {
- <<Create>> AwsMessage(CentralizedLogger)
+ Message getRawMessage(MetaRole,List<String>)
}

class cubibon.callAssistant.llm.message.DynamoDBMessage {
+ List<Map<String, AttributeValue>> toDynamoDB(List<Map<String, Any?>>)
- Map<String, AttributeValue> toDynamoDB(Map<String, Any?>)
- AttributeValue toAttributeValue(Any?)
+ Boolean isNullAttribute(AttributeValue)
- AttributeValue getErrorAttribute()
}

class cubibon.callAssistant.llm.message.MessageData$Companion {
+  SUMMARY_IDS_KEY
+  ATTRIBUTES_KEY
+  DATA_KEY
+  TIMING_KEY
}

class cubibon.callAssistant.llm.message.MessageData {
+ List<String>? summaryIds
- MutableList<MetaAttribute>? mutableAttributes
+ List<MetaAttribute>? attributes
- MutableMap<String, Any>? mutableData
+ Map<String, Any>? data
- MutableMap<MetaTiming, Long>? mutableTiming
+ Map<MetaTiming, Long>? timing
+ <<Create>> MessageData(CentralizedLogger)
+ void addAttributes(MetaAttribute)
+ void addData(String,Any)
+ void addTiming(MetaTiming,Long)
+ Map<String, Any?> toMap()
+ void toString()
+ Boolean equals(Any?)
+ void hashCode()
}


class cubibon.callAssistant.llm.message.MetaMessage$Builder {
+ Builder setRole(MetaRole)
+ Builder addContents(List<String>)
+ MessageWrapper.Builder<M> setId(String)
+ MetaMessage<M> public()
+ void toString()
+ void hashCode()
+ void equals(Any?)
}

class cubibon.callAssistant.llm.message.MetaMessage$Companion {
+ MessageWrapper.Builder<M> build(LlmMessage.Builder<M>,CentralizedLogger)
}

class cubibon.callAssistant.llm.message.MetaMessage {
-  mutableContents
+ List<String> contents
+ MetaRole role
+  metadata
+  id
+ M rawMessage
- <<Create>> MetaMessage(LlmMessage<M>,CentralizedLogger)
+ String toString()
+ Boolean equals(Any?)
+ Int hashCode()
}


class cubibon.callAssistant.llm.message.MessagesManager$Companion {
+  FAKE_MESSAGE_CONTENTS
}

class cubibon.callAssistant.llm.message.MessagesManager {
-  firstLlmMessageIdx
-  messageMapIdx
-  mutableMessages
-  lastSummaryMessageIdx
+ List<MessageWrapper<M>> metaMessages
+ List<M> messages
+ <<Create>> MessagesManager((logger: CentralizedLogger) -> MessageWrapper.Builder<M>)
+ String toString()
+ void addUser(List<String>)
+ void addAssistant(List<String>)
+ void addUser(String)
+ void addAssistant(String)
+ MessageWrapper<M>? addMessage(MetaRole,List<String>)
- MessageWrapper.Builder<M> addFistMessage(MetaRole,List<String>)
- MessageWrapper.Builder<M> addFollowingMessage(MetaRole,List<String>)
- MessageWrapper.Builder<M> addNewMessage(MetaRole,List<String>,Int?)
- Int getLasMessage((MessageWrapper.Builder<M>) -> Boolean)
+ Summarizing getSummaryInfo()
+ void addSummary(String,Summarizing)
+ MessageWrapper<M>? addSummary(List<String>,Summarizing)
+ MessageWrapper<M>? getLastSummary()
+ List<Map<String, Any>> toMessagesMap(Boolean,Boolean)
}


class cubibon.callAssistant.llm.message.Summarizing$SummarizingMessage {
+ <<Create>> SummarizingMessage(MetaRole,List<String>,Int,String)
+ <<Create>> SummarizingMessage(MessageWrapper.Builder<*>,Int)
+ String format()
}

class cubibon.callAssistant.llm.message.Summarizing$Formatter {
-  USER_TAG
-  ASSISTANT_TAG
-  SUMMARY_TAG
-  PREFIX
- (String) -> String TRANSFORMER
-  SEPARATOR
-  POSTFIX
- String SUMMARY_CLOSURE
- String CLOSURE
+ String userTag
+ String assistantTag
+ String summaryTag
+ String prefix
+ String postfix
+ String summaryClosure
+ String closure
+ String separator
+ (String) -> String transformer
+ void roleTag(MetaRole)
}


class cubibon.callAssistant.llm.message.Summarizing {
+ <<Create>> Summarizing(List<SummarizingMessage>,SummarizingMessage?)
+ String format(String,Boolean)
+ void toString()
+ List<Int> getIndexes()
+ void isEmpty()
}

enum cubibon.callAssistant.llm.message.MetaRole {
+  USER
+  ASSISTANT
+  SUMMARY
+ String toString()
}


interface cubibon.callAssistant.llm.message.LlmMessage$Builder {
+ LlmMessage<M> public()
}

interface cubibon.callAssistant.llm.message.LlmMessage {
+ M getRawMessage(MetaRole,List<String>)
}

enum cubibon.callAssistant.llm.message.MetaAttribute {
+  FAKE
+  MERGED
+ String toString()
}


enum cubibon.callAssistant.llm.message.MetaTiming {
+  CREATION
+  PLAY_START
+  PLAY_END
+  LISTEN_START
+  LISTEN_END
+  LLM_START
+  LLM_END
+ String toString()
}


interface cubibon.callAssistant.llm.message.MetaData {
+ List<String>? summaryIds
+ List<MetaAttribute>? attributes
+ Map<MetaTiming, Long>? timing
+ Map<String, Any>? data
+ void addTiming(MetaTiming,Long)
+ void addData(String,Any)
+ void addAttributes(MetaAttribute)
+ Map<String, Any?> toMap()
+ String toString()
+ Int hashCode()
+ Boolean equals(Any?)
}


class cubibon.callAssistant.llm.message.MessageWrapper$Builder$Companion {
+  MAP_ID_KEY
+  MAP_MESSAGE_KEY
+  MAP_ROLE_KEY
+  MAP_CONTENTS_KEY
+  MAP_METADATA_KEY
}

interface cubibon.callAssistant.llm.message.MessageWrapper$Builder {
+ Builder<M> setRole(MetaRole)
+ Builder<M> addContents(List<String>)
+ Builder<M> setId(String)
+ MessageWrapper<M> public()
+ Map<String, Any> toMap()
}

interface cubibon.callAssistant.llm.message.MessageWrapper {
+ String id
+ MetaRole role
+ List<String> contents
+ M rawMessage
+ MetaData metadata
+ String toString()
+ Int hashCode()
+ Boolean equals(Any?)
}




cubibon.callAssistant.llm.message.AwsMessage +.. cubibon.callAssistant.llm.message.AwsMessage$Builder
cubibon.callAssistant.llm.message.Builder <|.. cubibon.callAssistant.llm.message.AwsMessage$Builder
cubibon.callAssistant.llm.message.AwsMessage +.. cubibon.callAssistant.llm.message.AwsMessage$Companion
cubibon.callAssistant.llm.message.LlmMessage <|.. cubibon.callAssistant.llm.message.AwsMessage
cubibon.callAssistant.Loggable <|-- cubibon.callAssistant.llm.message.DynamoDBMessage
cubibon.callAssistant.llm.message.MessageData +.. cubibon.callAssistant.llm.message.MessageData$Companion
cubibon.callAssistant.llm.message.MetaData <|.. cubibon.callAssistant.llm.message.MessageData
cubibon.callAssistant.llm.message.MetaMessage +.. cubibon.callAssistant.llm.message.MetaMessage$Builder
cubibon.callAssistant.llm.message.Builder <|.. cubibon.callAssistant.llm.message.MetaMessage$Builder
cubibon.callAssistant.llm.message.MetaMessage +.. cubibon.callAssistant.llm.message.MetaMessage$Companion
cubibon.callAssistant.llm.message.MessageWrapper <|.. cubibon.callAssistant.llm.message.MetaMessage
cubibon.callAssistant.llm.message.MessagesManager +.. cubibon.callAssistant.llm.message.MessagesManager$Companion
cubibon.callAssistant.Loggable <|-- cubibon.callAssistant.llm.message.MessagesManager
cubibon.callAssistant.llm.message.Summarizing +.. cubibon.callAssistant.llm.message.Summarizing$SummarizingMessage
cubibon.callAssistant.llm.message.Summarizing +.. cubibon.callAssistant.llm.message.Summarizing$Formatter
cubibon.callAssistant.llm.message.LlmMessage +.. cubibon.callAssistant.llm.message.LlmMessage$Builder
cubibon.callAssistant.llm.message.Builder +.. cubibon.callAssistant.llm.message.Builder$Companion
cubibon.callAssistant.llm.message.MessageWrapper$Builder +.. cubibon.callAssistant.llm.message.MessageWrapper$Builder$Companion
cubibon.callAssistant.llm.message.MessageWrapper +.. cubibon.callAssistant.llm.message.MessageWrapper$Builder
@enduml