@startuml
class digital.boline.callAssistant.llm.AwsBedrockRequest$Companion {
+ List<SystemContentBlock> buildPrompts(List<String>)
+ List<SystemContentBlock> buildPrompts(String)
+ Message buildMessages(ConversationRole,String)
+ Message buildMessages(ConversationRole,List<String>)
+ Message buildUserMessages(String)
+ Message buildUserMessages(List<String>)
+ Message buildAssistantMessages(String)
+ Message buildAssistantMessages(List<String>)
}

class digital.boline.callAssistant.llm.AwsBedrockRequest {
+ <<Create>> AwsBedrockRequest(List<SystemContentBlock>,List<Message>,Int,Float,Float,String)
}

class digital.boline.callAssistant.llm.AwsBedrockResponse {
+ <<Create>> AwsBedrockResponse(String,Long,Int,Int,String)
}

class digital.boline.callAssistant.llm.AwsBedrock {
- BedrockRuntimeAsyncClient? client
- CompletableFuture<Void>? llmJob
- ConverseStreamResponseHandler? requestHandler
+ String sourceTag
+ void doActivate(String)
+ void doDeactivate(String)
- ConverseStreamResponseHandler buildResponseHandler()
+ void doComputeAsync(AwsBedrockRequest,String)
+ void doStop(String)
}


interface digital.boline.callAssistant.llm.LlmRequest {
+ P prompts
+ M messages
+ String modelName
+ Float temperature
+ Float topP
+ Int maxTokens
}

interface digital.boline.callAssistant.llm.LlmResponse {
+ String message
+ Long responseLatency
+ Int inputToken
+ Int outputToken
+ String sourceTag
}

abstract class digital.boline.callAssistant.llm.LlmService {
+  onResultCallbacks
}



digital.boline.callAssistant.llm.AwsBedrockRequest +.. digital.boline.callAssistant.llm.AwsBedrockRequest$Companion
digital.boline.callAssistant.llm.LlmRequest <|.. digital.boline.callAssistant.llm.AwsBedrockRequest
digital.boline.callAssistant.llm.LlmResponse <|.. digital.boline.callAssistant.llm.AwsBedrockResponse
digital.boline.callAssistant.llm.LlmService <|-- digital.boline.callAssistant.llm.AwsBedrock
digital.boline.callAssistant.CallbackInput <|.. digital.boline.callAssistant.llm.LlmResponse
digital.boline.callAssistant.ReusableService <|-- digital.boline.callAssistant.llm.LlmService
@enduml