@startuml
class cubibon.callAssistant.ServiceInterface$Companion {
+  UNKNOWN_SOURCE_TAG
}

interface cubibon.callAssistant.ServiceInterface {
+ AtomicBoolean isComputing
+ Boolean canCompute()
+ Boolean computeAsync(I,FrequentTimeout?,String)
+ Boolean wait(Timeout?,String)
+ Boolean stop(String)
+ void cancelScope()
}


class cubibon.callAssistant.Timeout$Companion {
# Long DEFAULT_TIMEOUT
#  DEFAULT_CALLBACK
# void timeoutToString(Long)
# void callbackToString(((String) -> Unit)?)
}


class cubibon.callAssistant.Timeout {
+ <<Create>> Timeout(Long,((String) -> Unit)?)
+ void invokeCallback(String)
+ void toString()
}

class cubibon.callAssistant.FrequentTimeout$Companion {
- Long DEFAULT_CHECK_PERIOD
}

class cubibon.callAssistant.FrequentTimeout {
+ <<Create>> FrequentTimeout(Long,Long,((String) -> Unit)?)
+ void toString()
}

enum cubibon.callAssistant.ErrorSource {
+  ACTIVATING
+  COMPUTING
+  TIMEOUT
+  WAITING
+  STOPPING
+  DEACTIVATING
+ <<Create>> ErrorSource(String)
}


class cubibon.callAssistant.ServiceError {
+ <<Create>> ServiceError(Throwable,ErrorSource,String)
}

abstract class cubibon.callAssistant.Service {
- Job? computingJob
- Job? timeoutJob
- AtomicLong? timeoutStart
#  isScopeCancelled
+  onErrorCallbacks
+  isComputing
+ <<Create>> Service(CoroutineScope)
# Boolean checkComputingState(Boolean,String)
+ Boolean canCompute()
+ Boolean computeAsync(I,FrequentTimeout?,String)
# void doComputeAsync(I,String)
- void doCheckTimeoutAsync(FrequentTimeout,String)
# void resetTimeout()
+ Boolean wait(Timeout?,String)
# void doWait(String)
+ Boolean stop(String)
# void doStop(String)
# void doThrow(Throwable,ErrorSource,String)
# Boolean? doThrow(ServiceError)
+ void cancelScope()
}


interface cubibon.callAssistant.ReusableServiceInterface {
+ AtomicBoolean isActive
+ Boolean canActivate()
+ Boolean activate(String)
+ Boolean canDeactivate()
+ Boolean deactivate(String)
}


abstract class cubibon.callAssistant.ReusableService {
+  isActive
+ <<Create>> ReusableService(CoroutineScope)
+ Boolean checkComputingState(Boolean,String)
- Boolean checkActiveState(Boolean,String)
+ Boolean canActivate()
+ Boolean activate(String)
# void doActivate(String)
+ Boolean canDeactivate()
+ Boolean deactivate(String)
# void doDeactivate(String)
}


interface cubibon.callAssistant.CallbackManagerInterface {
+ String add(((I) -> O))
+ void remove(((I) -> O))
+ void remove(String)
+ void clear()
+ Map<String, O> invoke(I)
+ ((I) -> O)? getCallbacks(String)
}

interface cubibon.callAssistant.CallbackInput {
+ String sourceTag
}

class cubibon.callAssistant.SimpleCallbackInput {
+ <<Create>> SimpleCallbackInput(String)
}

class cubibon.callAssistant.CallbackManager$Companion {
+ String getCallbackIdentifier(((I) -> O))
}

class cubibon.callAssistant.CallbackManager {
-  serviceName
- MutableMap<String, ((I) -> O)> callbacks
+ <<Create>> CallbackManager(CentralizedLogger)
+ ((I) -> O)? getCallbacks(String)
+ String add(((I) -> O))
+ void remove(((I) -> O))
+ void remove(String)
+ void clear()
+ Map<String, O> invoke(I)
}




cubibon.callAssistant.ServiceInterface +.. cubibon.callAssistant.ServiceInterface$Companion
cubibon.callAssistant.LoggableInterface <|.. cubibon.callAssistant.ServiceInterface
cubibon.callAssistant.Timeout +.. cubibon.callAssistant.Timeout$Companion
cubibon.callAssistant.FrequentTimeout +.. cubibon.callAssistant.FrequentTimeout$Companion
cubibon.callAssistant.Timeout <|-- cubibon.callAssistant.FrequentTimeout
cubibon.callAssistant.CallbackInput <|.. cubibon.callAssistant.ServiceError
cubibon.callAssistant.ServiceInterface <|.. cubibon.callAssistant.Service
cubibon.callAssistant.Loggable <|-- cubibon.callAssistant.Service
cubibon.callAssistant.ServiceInterface <|.. cubibon.callAssistant.ReusableServiceInterface
cubibon.callAssistant.ReusableServiceInterface <|.. cubibon.callAssistant.ReusableService
cubibon.callAssistant.Service <|-- cubibon.callAssistant.ReusableService
cubibon.callAssistant.CallbackInput <|.. cubibon.callAssistant.SimpleCallbackInput
cubibon.callAssistant.CallbackManager +.. cubibon.callAssistant.CallbackManager$Companion
cubibon.callAssistant.CallbackManagerInterface <|.. cubibon.callAssistant.CallbackManager
@enduml