@startuml
class digital.boline.callAssistant.ServiceInterface$Companion {
+  UNKNOWN_SOURCE_TAG
}

interface digital.boline.callAssistant.ServiceInterface {
+ AtomicBoolean isComputing
+ Boolean canCompute()
+ Boolean computeAsync(I,FrequentTimeout?,String)
+ Boolean wait(Timeout?,String)
+ Boolean stop(String)
+ void cancelScope()
}


class digital.boline.callAssistant.Timeout$Companion {
# Long DEFAULT_TIMEOUT
#  DEFAULT_CALLBACK
# void timeoutToString(Long)
# void callbackToString(((String) -> Unit)?)
}


class digital.boline.callAssistant.Timeout {
+ <<Create>> Timeout(Long,((String) -> Unit)?)
+ void invokeCallback(String)
+ void toString()
}

class digital.boline.callAssistant.FrequentTimeout$Companion {
- Long DEFAULT_CHECK_PERIOD
}

class digital.boline.callAssistant.FrequentTimeout {
+ <<Create>> FrequentTimeout(Long,Long,((String) -> Unit)?)
+ void toString()
}

enum digital.boline.callAssistant.ErrorSource {
+  ACTIVATING
+  COMPUTING
+  TIMEOUT
+  WAITING
+  STOPPING
+  DEACTIVATING
+ <<Create>> ErrorSource(String)
}


class digital.boline.callAssistant.ServiceError {
+ <<Create>> ServiceError(Throwable,ErrorSource,String)
}

abstract class digital.boline.callAssistant.Service {
- Job? computingJob
- Job? timeoutJob
- AtomicLong? timeoutStart
#  isScopeCancelled
+  onErrorCallbacks
+  isComputing
+ <<Create>> Service(CoroutineScope)
# Boolean checkComputingState(Boolean,String)
+ Boolean canCompute()
+ Boolean computeAsync(I,FrequentTimeout?,String)
# void doComputeAsync(I,String)
- void doCheckTimeoutAsync(FrequentTimeout,String)
# void resetTimeout()
+ Boolean wait(Timeout?,String)
# void doWait(String)
+ Boolean stop(String)
# void doStop(String)
# void doThrow(Throwable,ErrorSource,String)
# Boolean? doThrow(ServiceError)
+ void cancelScope()
}


interface digital.boline.callAssistant.ReusableServiceInterface {
+ AtomicBoolean isActive
+ Boolean canActivate()
+ Boolean activate(String)
+ Boolean canDeactivate()
+ Boolean deactivate(String)
}


abstract class digital.boline.callAssistant.ReusableService {
+  isActive
+ <<Create>> ReusableService(CoroutineScope)
+ Boolean checkComputingState(Boolean,String)
- Boolean checkActiveState(Boolean,String)
+ Boolean canActivate()
+ Boolean activate(String)
# void doActivate(String)
+ Boolean canDeactivate()
+ Boolean deactivate(String)
# void doDeactivate(String)
}


interface digital.boline.callAssistant.CallbackManagerInterface {
+ String add(((I) -> O))
+ void remove(((I) -> O))
+ void remove(String)
+ void clear()
+ Map<String, O> invoke(I)
+ ((I) -> O)? getCallbacks(String)
}

interface digital.boline.callAssistant.CallbackInput {
+ String sourceTag
}

class digital.boline.callAssistant.SimpleCallbackInput {
+ <<Create>> SimpleCallbackInput(String)
}

class digital.boline.callAssistant.CallbackManager$Companion {
+ String getCallbackIdentifier(((I) -> O))
}

class digital.boline.callAssistant.CallbackManager {
-  serviceName
- MutableMap<String, ((I) -> O)> callbacks
+ <<Create>> CallbackManager(CentralizedLogger)
+ ((I) -> O)? getCallbacks(String)
+ String add(((I) -> O))
+ void remove(((I) -> O))
+ void remove(String)
+ void clear()
+ Map<String, O> invoke(I)
}




digital.boline.callAssistant.ServiceInterface +.. digital.boline.callAssistant.ServiceInterface$Companion
digital.boline.callAssistant.LoggableInterface <|.. digital.boline.callAssistant.ServiceInterface
digital.boline.callAssistant.Timeout +.. digital.boline.callAssistant.Timeout$Companion
digital.boline.callAssistant.FrequentTimeout +.. digital.boline.callAssistant.FrequentTimeout$Companion
digital.boline.callAssistant.Timeout <|-- digital.boline.callAssistant.FrequentTimeout
digital.boline.callAssistant.CallbackInput <|.. digital.boline.callAssistant.ServiceError
digital.boline.callAssistant.ServiceInterface <|.. digital.boline.callAssistant.Service
digital.boline.callAssistant.Loggable <|-- digital.boline.callAssistant.Service
digital.boline.callAssistant.ServiceInterface <|.. digital.boline.callAssistant.ReusableServiceInterface
digital.boline.callAssistant.ReusableServiceInterface <|.. digital.boline.callAssistant.ReusableService
digital.boline.callAssistant.Service <|-- digital.boline.callAssistant.ReusableService
digital.boline.callAssistant.CallbackInput <|.. digital.boline.callAssistant.SimpleCallbackInput
digital.boline.callAssistant.CallbackManager +.. digital.boline.callAssistant.CallbackManager$Companion
digital.boline.callAssistant.CallbackManagerInterface <|.. digital.boline.callAssistant.CallbackManager
@enduml